f5:derle bagla calistir

derle:
	g++ -I "./include" -c ./src/main.cpp -o ./lib/main.o
	g++ -I "./include" -c ./src/Dugum.cpp -o ./lib/Dugum.o
	g++ -I "./include" -c ./src/BagliListe.cpp -o ./lib/BagliListe.o
bagla:
	g++ ./lib/main.o ./lib/Dugum.o ./lib/BagliListe.o -o ./bin/program

calistir:
	./bin/program.exe 